name: Build and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install GCC and OpenMP
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc

      # Build the C program
      - name: Build the program
        run: |
          gcc -o main src/*.c -fopenmp

      # Run the program with argument 1
      - name: Run with argument 1
        run: ./main 1

      # Run the program with argument 2
      - name: Run with argument 2
        run: ./main 2

      # Run the program with argument 3
      - name: Run with argument 3
        run: ./main 3
