
name: I_E_S_Population

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up GCC
    - name: Install GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
    # Step 3: Build the program
    - name: Build the matrix operations program
      run: |
        gcc -o main *.c -fopenmp 
    # Step 4: Run the program
    - name: Execute the program
      run: |
        ./main 1
        ./main 2
        ./main 3
